
   Nuwave\Lighthouse\Exceptions\DefinitionException 

  Failed to load type: SupplierPaginator. Make sure the type is present in your schema definition.

  at vendor\nuwave\lighthouse\src\Schema\TypeRegistry.php:79
    [90m 75[0m[90mÔûò [0m[35;1m    }[0m
    [90m 76[0m[90mÔûò [0m
    [90m 77[0m[90mÔûò [0m[35;1m    public static function [0m[39;1mfailedToLoadType[0m[35;1m([0m[39;1mstring $name[0m[35;1m): [0m[39;1mDefinitionException[0m
    [90m 78[0m[90mÔûò [0m[39;1m    [0m[35;1m{[0m
[31;1m  Ô×£ [0m[3;1m 79[0m[90mÔûò [0m[35;1m        return new [0m[39;1mDefinitionException[0m[35;1m([0m[37m"Failed to load type: [0m[35;1m{[0m[39;1m$name[0m[35;1m}[0m[37m. Make sure the type is present in your schema definition."[0m[35;1m);[0m
    [90m 80[0m[90mÔûò [0m[35;1m    }[0m
    [90m 81[0m[90mÔûò [0m
    [90m 82[0m[90mÔûò [0m[35;1m    public static function [0m[39;1mtriedToRegisterPresentType[0m[35;1m([0m[39;1mstring $name[0m[35;1m): [0m[39;1mDefinitionException[0m
    [90m 83[0m[90mÔûò [0m[39;1m    [0m[35;1m{[0m

  1   vendor\nuwave\lighthouse\src\Schema\TypeRegistry.php:105
      Nuwave\Lighthouse\Schema\TypeRegistry::failedToLoadType("SupplierPaginator")

  2   vendor\nuwave\lighthouse\src\Schema\AST\ExecutableTypeNodeConverter.php:37
      Nuwave\Lighthouse\Schema\TypeRegistry::get("SupplierPaginator")


