query TestProductCBD {
  productsCBD(first: 3) {
    paginatorInfo {
      currentPage
      total
      perPage
    }
    data {
      id
      name
      description
      price
      stock
      images
      image_urls
      image_metadata
      analysis_file
      analysis_file_url
      analysis_file_original_name
      analysis_file_size
      analysis_file_mime_type
      category_id
      category {
        id
        name
      }
      categories {
        id
        name
      }
      created_at
      updated_at
    }
  }
}
