# Test requête productsCBD page 1
query TestPage1 {
  productsCBD(first: 5, page: 1) {
    paginatorInfo {
      currentPage
      hasMorePages
      total
      perPage
      lastPage
    }
    data {
      id
      name
      created_at
    }
  }
}

# Test requête productsCBD page 2  
query TestPage2 {
  productsCBD(first: 5, page: 2) {
    paginatorInfo {
      currentPage
      hasMorePages
      total
      perPage
      lastPage
    }
    data {
      id
      name
      created_at
    }
  }
}
