type Supplier {
  id: ID!
  name: String!
  email: String
  phone: String
  products: [ProductCBD!]!
}

extend type ProductCBD {
  suppliers: [Supplier!]!
}

extend type Query {
  suppliers: [Supplier!]! 
    @guard(with: ["api"]) 
    @paginate(defaultCount: 20, maxCount: 100, model: "App\\Models\\Supplier")
  supplier(id: ID!): Supplier 
    @guard(with: ["api"]) 
    @can(ability: "view", model: "App\\Models\\Supplier")
    @find(model: "App\\Models\\Supplier")
}

extend type Mutation {
  createSupplier(name: String!, email: String, phone: String): Supplier
    @guard(with: ["api"])
    @field(resolver: "App\\Modules\\Supplier\\GraphQL\\Mutations\\SupplierMutator@createSupplier")

  attachSupplierToProduct(supplier_id: ID!, product_id: ID!): Supplier
    @guard(with: ["api"])
    @field(resolver: "App\\Modules\\Supplier\\GraphQL\\Mutations\\SupplierMutator@attachSupplierToProduct")

  detachSupplierFromProduct(supplier_id: ID!, product_id: ID!): Supplier
    @guard(with: ["api"])
    @field(resolver: "App\\Modules\\Supplier\\GraphQL\\Mutations\\SupplierMutator@detachSupplierFromProduct")
}