type Supplier {
  id: ID!
  name: String!
  email: String
  phone: String
  address: String
  website: String
  contact_person: String
  description: String
  products: [ProductCBD!]!
}


extend type ProductCBD {
  suppliers: [Supplier!]!
}

extend type Query {
  suppliers(first: Int, page: Int): [Supplier!]! 
    @guard(with: ["api"]) 
    @paginate(
      defaultCount: 20,
      maxCount: 100,
      builder: "App\\Modules\\Supplier\\GraphQL\\Queries\\SupplierQuery@suppliers"
    )
  supplier(id: ID!): Supplier 
    @guard(with: ["api"]) 
    @can(ability: "view", model: "App\\Models\\Supplier")
    @find(model: "App\\Models\\Supplier")
}

extend type Mutation {
  createSupplier(name: String!, email: String, phone: String, address: String, website: String, contact_person: String, description: String): Supplier
    @guard(with: ["api"])
    @field(resolver: "App\\Modules\\Supplier\\GraphQL\\Mutations\\SupplierMutator@createSupplier")

  attachSupplierToProduct(supplier_id: ID!, product_id: ID!): Supplier
    @guard(with: ["api"])
    @field(resolver: "App\\Modules\\Supplier\\GraphQL\\Mutations\\SupplierMutator@attachSupplierToProduct")

  detachSupplierFromProduct(supplier_id: ID!, product_id: ID!): Supplier
    @guard(with: ["api"])
    @field(resolver: "App\\Modules\\Supplier\\GraphQL\\Mutations\\SupplierMutator@detachSupplierFromProduct")
}